name: Rakamak
main: com.piwany.erwyn.rakamak.Rakamak
version: 3.6.1
website: http://www.odyocraft.fr
description: Provides authentication possibilities with online-mode = false
authors: [Erwyn & Dorpaxio]
commands:
  register:
    description: Set your password.
    usage: /<command> <password>
  login:
    description: To try authentication.
    usage: /<command> <password>
  changepass:
    description: Change your password.
    usage: /<command> <currentpassword> <newpassword>