name: Rakamak
main: com.piwany.erwyn.rakamak.Rakamak
version: 4.0.0
website: http://www.odyocraft.fr
description: Provides authentication possibilities with online-mode = false
authors: [alecgorge, Erwyn & Dorpaxio]
commands:
  register:
    description: Set your password.
    usage: /<command> <password>
  login:
    description: To try authentication.
    usage: /<command> <password>
  changepass:
    description: Change your password.
    usage: /<command> <currentpassword> <newpassword>